# Generated by Django 3.0.3 on 2020-03-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('dob', models.DateTimeField()),
                ('adult', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('tags', models.CharField(max_length=32)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meme_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('tags', models.CharField(max_length=32)),
                ('ratedusername', models.ManyToManyField(related_name='rateduser', to='meme_app.User')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createduser', to='meme_app.User')),
            ],
        ),
    ]
