# Generated by Django 3.0.3 on 2020-03-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=-1)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meme_app.Meme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meme_app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=-1)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meme_app.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meme_app.UserProfile')),
            ],
        ),
    ]
