# Generated by Django 3.0.3 on 2020-03-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
