# Generated by Django 3.0.4 on 2020-03-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='category_str',
            field=models.CharField(default='', max_length=64),
        ),
    ]
