# Generated by Django 3.0.3 on 2020-03-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0002_commentrating_memerating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentrating',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='memerating',
            unique_together={('user', 'meme')},
        ),
    ]
