# Generated by Django 2.2.3 on 2020-03-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0002_auto_20200318_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='picture',
            field=models.ImageField(blank=True, upload_to='meme_images'),
        ),
    ]
