# Generated by Django 2.2.3 on 2020-03-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0002_auto_20200320_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='username',
            new_name='user',
        ),
    ]
