# Generated by Django 3.0.3 on 2020-03-29 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0003_auto_20200328_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.CharField(max_length=64)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meme_app.Meme')),
            ],
        ),
    ]
