# Generated by Django 3.0.3 on 2020-03-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0003_auto_20200328_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='category_str',
        ),
    ]
