# Generated by Django 3.0.3 on 2020-03-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0003_auto_20200321_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
