# Generated by Django 3.0.4 on 2020-03-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0003_auto_20200329_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memerating',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
